# Generated by Django 3.2 on 2021-10-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_type',
            field=models.CharField(choices=[('places', 'Places'), ('hilly', 'Hilly'), ('beach', 'Beach'), ('Religious', 'Religious'), ('resort', 'Resort'), ('Culture and Heritage', 'Culture and Heritage')], max_length=20),
        ),
    ]
