# Generated by Django 3.2 on 2021-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
