# Generated by Django 3.2 on 2021-10-18 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_places_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='places',
            name='description',
            field=models.TextField(default='Description', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_type',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('Islands', 'Islands'), ('Beach resorts', 'Beach resorts'), ('Secluded beaches', 'Secluded beaches'), ('Mountain', 'Mountain'), ('Forest', 'Forest'), ('Countryside', 'Countryside'), ('Town', 'Town'), ('City', 'City'), ('Winter sport', 'Winter sport'), ('Culture and Heritage', 'Culture and Heritage'), ('Religious', 'Religious')], max_length=20),
        ),
        migrations.AlterField(
            model_name='places',
            name='subject',
            field=models.CharField(max_length=25),
        ),
    ]
