# Generated by Django 3.2 on 2021-11-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_type',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('District', 'District'), ('Islands', 'Islands'), ('Beach', 'Beach'), ('Beach resorts', 'Beach resorts'), ('Secluded beaches', 'Secluded beaches'), ('Mountain', 'Mountain'), ('Forest', 'Forest'), ('Dessert', 'Dessert'), ('Countryside', 'Countryside'), ('Town', 'Town'), ('City', 'City'), ('Winter sport', 'Winter sport'), ('Culture and Heritage', 'Culture and Heritage'), ('Religious', 'Religious'), ('Museum', 'Museum'), ('Educational', 'Educational')], max_length=20),
        ),
    ]
