# Generated by Django 3.2 on 2021-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210819_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='image',
            field=models.ImageField(upload_to='place'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(upload_to='user_dp'),
        ),
    ]
