# Generated by Django 3.2 on 2021-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210819_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(default=None, upload_to='user_dp'),
        ),
    ]
