# Generated by Django 3.2 on 2021-09-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=20)),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review', verbose_name='r_id_FK')),
            ],
        ),
        migrations.CreateModel(
            name='Review_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_pic', models.ImageField(upload_to='review')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review', verbose_name='r_id_FK')),
            ],
        ),
        migrations.CreateModel(
            name='Place_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.places', verbose_name='M1_place')),
                ('spm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.places', verbose_name='S1_place')),
            ],
        ),
    ]
