# Generated by Django 3.2 on 2021-09-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210918_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_type',
            field=models.CharField(choices=[('hilly', 'Hilly'), ('beach', 'Beach'), ('Religious', 'Religious'), ('resort', 'Resort')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review', verbose_name='r_id_FK')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='u_id_FK')),
            ],
        ),
    ]
