# Generated by Django 3.2 on 2021-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_place_places_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_type',
            field=models.CharField(choices=[('places', 'Places'), ('hilly', 'Hilly'), ('beach', 'Beach'), ('Religious', 'Religious'), ('resort', 'Resort')], max_length=20),
        ),
    ]
